#Variavel
$script_mysql = <<-SCRIPT
    apt-get update && \
    apt-get install -y mysql-server-5.7 && \
    mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    # #Maquina Virtual 1 - MySQL + shell
    # config.vm.define "mysqldb" do |mysql|
    
    #     #Configuração de Rede
    #     mysql.vm.network "private_network", type: "dhcp"
        
    #     # Scripts Shell
    #     mysql.vm.provision "shell", 
    #         inline: "cat /configs/id_rsa.pub >> .ssh/authorized_keys"
        
    #         mysql.vm.provision "shell", inline: $script_mysql
    
    #         mysql.vm.provision "shell", 
    #         inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
    
    #         mysql.vm.provision "shell", 
    #         inline: "service mysql restart"
    
    #     #Pastas Comartilhadas
    #     mysql.vm.synced_folder "./configs", "/configs"
    #     mysql.vm.synced_folder ".", "/vagrant", disabled: true

    # end 

    # Máquina Virtual 2 - PHP + puppet
    # config.vm.define "phpweb" do |phpweb|
    
    #     #Configuração de Rede
    #     phpweb.vm.network "forwarded_port", guest: 8888, host: 8888
    #     phpweb.vm.network "private_network", ip: "172.28.128.9"

    #     #Instalando Puppet
    #     phpweb.vm.provision "shell",
    #         inline: "apt-get update && apt-get install -y puppet"

    #     phpweb.vm.provision "puppet" do |puppet|
    #         puppet.manifests_path = "./configs/manifests"
    #         puppet.manifest_file = "phpweb.pp"
    #     end

    # end

    # Máquina Virtual 3 - MySQL
    config.vm.define "mysqlserver" do |mysqlserver|
        
        mysqlserver.vm.provider "virtualbox" do |vb|
            vb.memory = 512
            vb.cpus = 2
            vb.name = "ubuntu_bionic_mysql"
        end

        # Configuração de Rede
        mysqlserver.vm.network "private_network", type: "dhcp"

        # Scripts Shell
        # Script para copiar chave publica do hosto para a maquina virtual
        mysqlserver.vm.provision "shell", 
        inline: "cat /vagrant/configs/id_rsa.pub >> .ssh/authorized_keys"

    end

    # Máquina Virtual 4 - Ansible
    # Esta máquina vai configurar a Maquina Virtual 3 - MySQL
    config.vm.define "ansible" do |ansible|
       
        #Configuração de Rede
        ansible.vm.network "private_network", type: "dhcp"

        # Scripts Shell
        # Script para copiar chave privada do host para a maquina virtual
        ansible.vm.provision "shell", 
        inline: "cp /vagrant/id_rsa /home/vagrant && \
                chmod 600 /home/vagrant/id_rsa"

        # Scripts Shell
        ansible.vm.provision "shell", 
            inline: "apt-get update && \
            apt-get install -y software-properties-common && \
            apt-add-repository --yes --update ppa:ansible/ansible && \
            apt-get install -y ansible"


        ansible.vm.provision "shell", 
            inline: "ansible-playbook -i /vagrant/configs/ansible/hosts \
                    /vagrant/configs/ansible/playbook.yml"

    end
    
end