#Variavel
$script_mysql = <<-SCRIPT
    apt-get update && \
    apt-get install -y mysql-server-5.7 && \
    mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    #Maquina Virtual 1 - MySQL
    config.vm.define "mysqldb" do |mysql|
    
        #Configuração de Rede
        mysql.vm.network "private_network", type: "dhcp"
        
        # Scripts Shell
        mysql.vm.provision "shell", 
            inline: "cat /configs/id_rsa.pub >> .ssh/authorized_keys"
        
            mysql.vm.provision "shell", inline: $script_mysql
    
            mysql.vm.provision "shell", 
            inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
    
            mysql.vm.provision "shell", 
            inline: "service mysql restart"
    
        #Pastas Comartilhadas
        mysql.vm.synced_folder "./configs", "/configs"
        mysql.vm.synced_folder ".", "/vagrant", disabled: true

    end 

    #Maquina Virtual 2 - PHP
    config.vm.define "phpweb" do |phpweb|
    
        #Configuração de Rede
        phpweb.vm.network "forwarded_port", guest: 80, host: 8089
        phpweb.vm.network "private_network", type: "dhcp"

    end

end